### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by nimasaj** [farrokhi/adblock-iran#10]
### Request
I would like to contribute to this list by making enhancements as well as adding more rules.
I have already developed a list which blocks most advertisements in Farsi/Iranian websites, by considering the least possible false positives and being effective at the same time, that could be found in following address:

### Address
`https://github.com/nimasaj/uBO_Filterlist`

### Note
My contribution does not necessarily mean that my filter list will be merged thoroughly with this list.
 

Eagerly awaiting your response
 

Thanks in advance
Nima Sajedi

**Comment by farrokhi** [comment]
Thank you very much for expressing your interest and your recent contributions. Please kindly submit your pull requests and I will verify and merge them quickly.
