### ISSUE TITLE
سایت سافت۹۸

### ISSUE THREAD

**Issue by FTABoy** [farrokhi/adblock-iran#16]
با سلام. سایت معروفه سافت۹۸ فعال بودن اد بلاک(یوبلاک اورجین) را تشخیص میدهد و در نتیجه دو مشکل به وجود می آید:
۱- لینک دانلود برنامه ها نمایش داده نمیشود و عبارت : 
برای مشاهده لیست دانلود باید جاوا اسکریپت مرورگر خود را فعال کنید و یا افزونه حذف تبلیغات را غیرفعال کنید و بعد روی این قسمت کلیک کنید.
را نشان میدهد.
۲- سربرگ مطالب موبایل (آخرین ارسال ها) باز نمیشود.
از فیلتره شما استفاده میکنم. راه حلی وجود داره ؟
به عنوان مثال به این صفحه مراجعه کنید و بخش لیست دانلود را ببینید:
https://soft98.ir/software/Cd-dvd-tools/143-dvdfab.html

**Comment by MasterKia** [comment]
https://github.com/DRSDavidSoft/user-scripts/issues/1
