### ISSUE TITLE
soft98.ir

### ISSUE THREAD

**Issue by BlazDT** [farrokhi/adblock-iran#17]
https://soft98.ir/internet/download-manager/4-internet-download-manager-full.html

Download links are missing.

Fix:

`@@||soft98.ir/templates/soft98_default/js/jquery.min.js`

https://github.com/AdguardTeam/AdguardFilters/issues/21151

**Comment by farrokhi** [comment]
@BlazDT that file is not the actual jquery code and used to serve ads in addition to jquery functionality. Users will need to whitelist the site if they need to access the site (and see all the ads).

**Comment by BlazDT** [comment]
Then the ads must be dealt with other rules as when blocking that url is breaking the site‘s functionality, it should be unblocked.

**Comment by farrokhi** [comment]
Fixed in 4928412

**Comment by mrhappy2077** [comment]
سلام دوستان
درآپدیت جدید سایت این پیغام برای من میاد 👍 
افزونه حذف تبلیغات یا Adgaurd را در مرورگر غیرفعال کنید، سپس F5 بزنید.

اسکریپت جدیدی نیست من تو برنامه ادگارد بزنم دوباره ؟
