### ISSUE TITLE
Conflicts with Gmail webapp

### ISSUE THREAD

**Issue by sepehr** [farrokhi/adblock-iran#2]
When installed, email bodies in the Gmail webapp is completely removed.

**Comment by farrokhi** [comment]
It seems to be a rule in EasyList that blocks certain iframes and hides some elements in gmail. I disabled EasyList and it was back to normal. You can report it here: https://easylist.to/

**Comment by sepehr** [comment]
I don't think so; I have no problem with Gmail when the EasyList is enabled. But when I enable the `adblock-iran` filter, then the problem happens.

**Comment by fffaraz** [comment]
I confirm that it happened to me too and I had to disable my uBlock for gmail but I didn't know which list is causing this.

**Comment by farrokhi** [comment]
I updated the list a few minutes ago and believe that it should be resolved now. Please confirm.

**Comment by fffaraz** [comment]
Seems to work fine for me. Thank you!

**Comment by sepehr** [comment]
It's working now. Thank you for the quick fix.
