### ISSUE TITLE
Please add this too.

### ISSUE THREAD

**Issue by mortazaeek** [farrokhi/adblock-iran#23]
Hello.

I've checked and see that awesome list.
You did it great.
All Iranian internet user at least once face to **peyvandha** page undoubtedly!
below in the order is main, alternate and redirect.

- [http://10.10.34.34/](url)
- [http://10.10.34.35/](url) (_alt_)
- [http://peyvandha.ir/](url) (_redirect_)

> Sorry if I've sending this in wrong place.

Best Regards
Kamyar

**Comment by farrokhi** [comment]
sorry, the goal here is to block ads. However I suggest you null route those networks in your router/CPE/host.
