### ISSUE TITLE
Filtering ###popup too expensive

### ISSUE THREAD

**Issue by LynxChaus** [farrokhi/adblock-iran#4]
Filtering ###popup too expensive, every "web-designer" use popup as lables for modal windows/etc.
I spent hours to find - why worked yesterday web-tool not working today. Please, remove this.

**Comment by aaomidi** [comment]
Just use a different name? Popup shouldn't be used for proper stuff.

**Comment by farrokhi** [comment]
Would you mind sharing some example of widely used websites that are broken by this rule?

**Comment by Firminator** [comment]
![screenshot from 2017-10-26 12-50-59](https://user-images.githubusercontent.com/12078737/32065997-5f613934-ba4c-11e7-9dda-565f7e6a1b60.png)

**Comment by nimasaj** [comment]
I agree that this cosmetic filter is too broad and generic. It could be edited to either be applied only on specific websites, or get narrowed down and be less generic.

**Comment by Npuria** [comment]
تو زومیت هیچ عکسی باز نمیشه!!؟

**Comment by farrokhi** [comment]
Fixed
