### ISSUE TITLE
add domains to addguard DNS list

### ISSUE THREAD

**Issue by mmrabbani** [farrokhi/adblock-iran#41]
Hello
Can you add all domain lists to adguard DNS list? so these websites will be filtered without need to any app (I know some rules are addresses that cannot be filtered by DNS).

**Comment by farrokhi** [comment]
This cannot be done since most of these rules granularly filter our directories, etc. Blocking a whole domain does not work in most cases. However I have a list of domains that can be safely blocked (pihole.txt), which can be useful if you are running your own dns blocklist / pihole.
