### ISSUE TITLE
Website login issue

### ISSUE THREAD

**Issue by choomchichi** [farrokhi/adblock-iran#49]
Hi
There is a problem with login button on this website:
https://www.tavangary.com/
I checked different possibilities and the issue is related to the adblock-iran filter list in uBlock.
Thanks.

**Comment by choomchichi** [comment]
Hi,
The same issue on this website:
https://p2k.co/

uBlock blocks pop-up messages in these websites.
Thanks.

**Comment by farrokhi** [comment]
fixed

**Comment by choomchichi** [comment]
Thanks a lot.
