### ISSUE TITLE
New AD

### ISSUE THREAD

**Issue by mahdiamzx** [farrokhi/adblock-iran#66]
https://click.digiato.com/

**Comment by MasterKia** [comment]
> https://click.digiato.com/

This filterlist prevent that ad:
https://raw.githubusercontent.com/SlashArash/adblockfa/master/adblockfa.txt

**Comment by MasterKia** [comment]
درود @mahdiamzx 
من همه فیلتر های لیست Adblock-Iran رو بازنویسی کردم و لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) رو به وجود آوردم.
امروز لیست PersianBlocker به لیست های پیشفرض uBlock Origin [افزوده](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد.
