### ISSUE TITLE
jobinja forced login banner

### ISSUE THREAD

**Issue by mortezadadgar** [farrokhi/adblock-iran#80]
Hey,
jobinja forces users to login for using their website by showing a messagebox in the middle and blurred background for example this page [jobinja annoyance](https://jobinja.ir/companies/faraboom/jobs/Rm1Z/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3-%D8%AC%D8%A7%D9%88%D8%A7-java-%D8%AF%D8%B1-%D9%81%D8%B1%D8%A7%D8%A8%D9%88%D9%85?_ref=18)
messagebox can be blocked but blocking .c-forceToLogin__overlay blocks the whole page behind it

**Comment by MasterKia** [comment]
It might get fixed upstream: https://github.com/uBlockOrigin/uAssets/issues/12279

**Comment by MasterKia** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3126a03b7159077f47ce16dba45906688cf2af86
It's fixed, enable the _uBlock filters – Annoyances_ filterlist in uBlock Origin's settings.

**Comment by mortezadadgar** [comment]
Thanks! works perfectly

**Comment by MasterKia** [comment]
درود @mortezadadgar 
من همه فیلتر های لیست Adblock-Iran رو بازنویسی کردم و لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) رو به وجود آوردم.
امروز لیست PersianBlocker به لیست های پیشفرض uBlock Origin [افزوده](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد.
